import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getSettings } from './settings.js';
import { ActivityLogger, shouldIgnore } from './activity-logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// AI tool pointer file content
const POINTER_CONTENT = `<!-- AUTO-GENERATED by ai-checkpoint. Do not edit. Source of truth: AGENTS.md -->
Read and follow all instructions in AGENTS.md
`;

// Template-restorable files (relative to project root → template name)
const TEMPLATE_RESTORABLE = {
  [path.join('.agents', 'AGENTS.md')]: 'AGENTS.md',
  [path.join('.agents', 'RULES.md')]: 'RULES.md',
  [path.join('.agents', 'SYSTEM_GUIDE.md')]: 'SYSTEM_GUIDE.md',
};

// Pointer files that can be regenerated
const POINTER_FILES = [
  'CLAUDE.md',
  'GEMINI.md',
  '.cursorrules',
  '.windsurfrules',
  '.clinerules',
];

// Files that only get a warning (data files — restore would lose data)
const WARN_ONLY_FILES = [
  path.join('.agents', 'PROGRESS.md'),
];

// ──────────────────────────────────────────────
// SSE Client Manager
// ──────────────────────────────────────────────

class SSEClientManager {
  constructor() {
    // projectId → Set<res>
    this.clients = new Map();
  }

  addClient(projectId, res) {
    if (!this.clients.has(projectId)) {
      this.clients.set(projectId, new Set());
    }
    this.clients.get(projectId).add(res);
  }

  removeClient(projectId, res) {
    const set = this.clients.get(projectId);
    if (set) {
      set.delete(res);
      if (set.size === 0) this.clients.delete(projectId);
    }
  }

  broadcast(projectId, event, data) {
    const set = this.clients.get(projectId);
    if (!set || set.size === 0) return;
    const payload = `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
    for (const res of set) {
      try { res.write(payload); } catch (e) { /* client gone */ }
    }
  }

  broadcastAll(event, data) {
    const payload = `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
    for (const [, set] of this.clients) {
      for (const res of set) {
        try { res.write(payload); } catch (e) { /* client gone */ }
      }
    }
  }
}

// ──────────────────────────────────────────────
// Project File Watcher
// ──────────────────────────────────────────────

class ProjectWatcher {
  constructor(projectId, projectPath, sseManager, templatesDir) {
    this.projectId = projectId;
    this.projectPath = projectPath;
    this.sseManager = sseManager;
    this.templatesDir = templatesDir;
    this.watchers = [];
    this.debounceTimers = new Map();
    this.isRestoring = false; // prevent loops when we restore a file
    this.logger = new ActivityLogger(projectPath);
  }

  start() {
    this.watchDirectory(path.join(this.projectPath, '.agents'), '.agents');
    this.watchDirectory(path.join(this.projectPath, 'plan'), 'plan');
    this.watchRootPointerFiles();
    this.watchProjectFiles();
    console.log(`👁️  Watching: ${this.projectPath}`);
  }

  stop() {
    for (const w of this.watchers) {
      try { w.close(); } catch (e) { /* already closed */ }
    }
    this.watchers = [];
    for (const timer of this.debounceTimers.values()) {
      clearTimeout(timer);
    }
    this.debounceTimers.clear();
  }

  watchDirectory(dirPath, prefix) {
    if (!fs.existsSync(dirPath)) return;
    try {
      const watcher = fs.watch(dirPath, { recursive: false }, (eventType, filename) => {
        if (!filename || this.isRestoring) return;
        const relativePath = path.join(prefix, filename);
        this.debounce(relativePath, () => this.handleFileEvent(relativePath, eventType));
      });
      this.watchers.push(watcher);
      watcher.on('error', (err) => {
        console.error(`⚠️ Watcher error on ${dirPath}:`, err.message);
      });
    } catch (e) {
      console.error(`⚠️ Failed to watch ${dirPath}:`, e.message);
    }
  }

  watchRootPointerFiles() {
    // Watch root directory for pointer file changes
    try {
      const watcher = fs.watch(this.projectPath, { recursive: false }, (eventType, filename) => {
        if (!filename || this.isRestoring) return;
        if (POINTER_FILES.includes(filename)) {
          this.debounce(filename, () => this.handleFileEvent(filename, eventType));
        }
        // Also watch for root AGENTS.md
        if (filename === 'AGENTS.md') {
          this.debounce(filename, () => this.handleRootAgentsChange(eventType));
        }
      });
      this.watchers.push(watcher);
      watcher.on('error', () => { /* root dir watcher error — non-critical */ });
    } catch (e) {
      // Non-critical — root watching is optional
    }
  }

  debounce(key, fn) {
    if (this.debounceTimers.has(key)) {
      clearTimeout(this.debounceTimers.get(key));
    }
    this.debounceTimers.set(key, setTimeout(() => {
      this.debounceTimers.delete(key);
      fn();
    }, 300));
  }

  handleFileEvent(relativePath, eventType) {
    const fullPath = path.join(this.projectPath, relativePath);
    const exists = fs.existsSync(fullPath);

    if (!exists) {
      // File was DELETED
      this.logger.log('DELETED', relativePath);
      this.handleDeletion(relativePath);
    } else {
      // File was CREATED or MODIFIED
      const action = eventType === 'rename' ? 'CREATED' : 'MODIFIED';
      this.logger.log(action, relativePath);
      this.handleChange(relativePath);
    }

    // Broadcast activity-log event to dashboard
    this.sseManager.broadcast(this.projectId, 'activity-log', {
      ts: new Date().toISOString(),
      action: exists ? (eventType === 'rename' ? 'CREATED' : 'MODIFIED') : 'DELETED',
      file: relativePath,
    });
  }

  handleDeletion(relativePath) {
    // 1. Template-restorable files (.agents/AGENTS.md, etc.)
    const templateName = TEMPLATE_RESTORABLE[relativePath];
    if (templateName) {
      this.restoreFromTemplate(relativePath, templateName);
      return;
    }

    // 2. Pointer files (CLAUDE.md, .cursorrules, etc.)
    const basename = path.basename(relativePath);
    if (POINTER_FILES.includes(basename) && !relativePath.includes(path.sep)) {
      this.restorePointerFile(relativePath);
      return;
    }

    // 3. Warn-only files (PROGRESS.md)
    if (WARN_ONLY_FILES.includes(relativePath)) {
      this.sseManager.broadcast(this.projectId, 'file-deleted-warning', {
        file: relativePath,
        message: `⚠️ ${relativePath} was deleted! Accept to recreate from template.`,
        canRestore: true,
      });
      return;
    }

    // 4. Plan files deleted — just notify UI to refresh
    if (relativePath.startsWith('plan' + path.sep) && relativePath.endsWith('.md')) {
      this.sseManager.broadcast(this.projectId, 'plan-deleted', {
        file: relativePath,
      });
      return;
    }
  }

  handleChange(relativePath) {
    // Plan file changed → instant UI refresh
    if (relativePath.startsWith('plan' + path.sep) && relativePath.endsWith('.md')) {
      this.sseManager.broadcast(this.projectId, 'plan-updated', {
        file: relativePath,
      });
      return;
    }

    // PROGRESS.md changed → instant UI refresh
    if (relativePath === path.join('.agents', 'PROGRESS.md')) {
      this.sseManager.broadcast(this.projectId, 'progress-updated', {
        file: relativePath,
      });
      return;
    }

    // AGENTS.md or RULES.md changed → notify
    if (relativePath === path.join('.agents', 'AGENTS.md') || relativePath === path.join('.agents', 'RULES.md')) {
      this.sseManager.broadcast(this.projectId, 'config-updated', {
        file: relativePath,
      });
    }
  }

  handleRootAgentsChange(eventType) {
    const fullPath = path.join(this.projectPath, 'AGENTS.md');
    if (!fs.existsSync(fullPath)) {
      // Root AGENTS.md deleted — not critical, but notify
      this.sseManager.broadcast(this.projectId, 'file-deleted-warning', {
        file: 'AGENTS.md',
        message: 'Root AGENTS.md was deleted.',
        canRestore: false,
      });
    }
  }

  restoreFromTemplate(relativePath, templateName) {
    const templatePath = path.join(this.templatesDir, templateName);
    const destPath = path.join(this.projectPath, relativePath);

    if (!fs.existsSync(templatePath)) {
      console.error(`⚠️ Template not found: ${templatePath}`);
      return;
    }

    this.isRestoring = true;
    try {
      // Ensure directory exists
      fs.mkdirSync(path.dirname(destPath), { recursive: true });
      fs.copyFileSync(templatePath, destPath);
      console.log(`🔄 Auto-restored: ${relativePath}`);
      this.logger.log('RESTORED', relativePath);
      this.sseManager.broadcast(this.projectId, 'file-restored', {
        file: relativePath,
        message: `🔄 ${relativePath} auto-restored from template`,
      });
    } catch (e) {
      console.error(`⚠️ Failed to restore ${relativePath}:`, e.message);
    } finally {
      setTimeout(() => { this.isRestoring = false; }, 500);
    }
  }

  restorePointerFile(filename) {
    const destPath = path.join(this.projectPath, filename);

    this.isRestoring = true;
    try {
      fs.writeFileSync(destPath, POINTER_CONTENT, 'utf8');
      console.log(`🔄 Auto-restored pointer: ${filename}`);
      this.logger.log('RESTORED', filename);
      this.sseManager.broadcast(this.projectId, 'file-restored', {
        file: filename,
        message: `🔄 ${filename} auto-restored`,
      });
    } catch (e) {
      console.error(`⚠️ Failed to restore pointer ${filename}:`, e.message);
    } finally {
      setTimeout(() => { this.isRestoring = false; }, 500);
    }
  }

  watchProjectFiles() {
    // Watch entire project recursively for activity logging
    // macOS FSEvents handles recursive watching efficiently
    try {
      const watcher = fs.watch(this.projectPath, { recursive: true }, (eventType, filename) => {
        if (!filename || this.isRestoring) return;
        // Skip directories already watched specifically (.agents and plan)
        if (filename.startsWith('.agents' + path.sep) ||
            filename === '.agents' ||
            filename.startsWith('plan' + path.sep) ||
            filename === 'plan') {
          return;
        }
        // Skip ignored patterns and extensions
        if (shouldIgnore(filename)) return;
        this.debounce('proj:' + filename, () => {
          const fullPath = path.join(this.projectPath, filename);
          const exists = fs.existsSync(fullPath);
          const action = exists ? (eventType === 'rename' ? 'CREATED' : 'MODIFIED') : 'DELETED';
          this.logger.log(action, filename);
          this.sseManager.broadcast(this.projectId, 'activity-log', {
            ts: new Date().toISOString(),
            action: action,
            file: filename,
          });
        });
      });
      this.watchers.push(watcher);
      watcher.on('error', () => { /* non-critical */ });
    } catch (e) {
      // Recursive watching may not be supported on all platforms
      console.error('⚠️ Recursive watch not available:', e.message);
    }
  }
}

// ──────────────────────────────────────────────
// Watcher Manager (manages all project watchers)
// ──────────────────────────────────────────────

class WatcherManager {
  constructor() {
    this.sseManager = new SSEClientManager();
    this.watchers = new Map(); // projectId → ProjectWatcher
    this.templatesDir = path.resolve(__dirname, '..', '..', '..', 'templates');
  }

  getOrCreateWatcher(projectId, projectPath) {
    if (this.watchers.has(projectId)) {
      return this.watchers.get(projectId);
    }
    const watcher = new ProjectWatcher(projectId, projectPath, this.sseManager, this.templatesDir);
    watcher.start();
    this.watchers.set(projectId, watcher);
    return watcher;
  }

  stopWatcher(projectId) {
    const watcher = this.watchers.get(projectId);
    if (watcher) {
      watcher.stop();
      this.watchers.delete(projectId);
    }
  }

  stopAll() {
    for (const [id, watcher] of this.watchers) {
      watcher.stop();
    }
    this.watchers.clear();
  }

  // Restore PROGRESS.md from template (called when user accepts warning)
  restoreProgressFromTemplate(projectId) {
    const watcher = this.watchers.get(projectId);
    if (!watcher) return false;

    const templatePath = path.join(this.templatesDir, 'PROGRESS.md');
    const destPath = path.join(watcher.projectPath, '.agents', 'PROGRESS.md');

    if (!fs.existsSync(templatePath)) return false;

    try {
      fs.mkdirSync(path.dirname(destPath), { recursive: true });
      fs.copyFileSync(templatePath, destPath);
      console.log(`🔄 PROGRESS.md restored for project ${projectId}`);
      this.sseManager.broadcast(projectId, 'file-restored', {
        file: '.agents/PROGRESS.md',
        message: '🔄 PROGRESS.md recreated from template',
      });
      return true;
    } catch (e) {
      console.error(`⚠️ Failed to restore PROGRESS.md:`, e.message);
      return false;
    }
  }

  // Generate pointer files for all AI tools
  generatePointerFiles(projectPath) {
    const copilotDir = path.join(projectPath, '.github');

    for (const file of POINTER_FILES) {
      const destPath = path.join(projectPath, file);
      if (!fs.existsSync(destPath)) {
        try {
          fs.writeFileSync(destPath, POINTER_CONTENT, 'utf8');
          console.log(`  ✔ Created pointer: ${file}`);
        } catch (e) {
          console.error(`  ⚠️ Failed to create ${file}:`, e.message);
        }
      }
    }

    // GitHub Copilot special path
    const copilotFile = path.join(copilotDir, 'copilot-instructions.md');
    if (!fs.existsSync(copilotFile)) {
      try {
        fs.mkdirSync(copilotDir, { recursive: true });
        fs.writeFileSync(copilotFile, POINTER_CONTENT, 'utf8');
        console.log(`  ✔ Created pointer: .github/copilot-instructions.md`);
      } catch (e) {
        console.error(`  ⚠️ Failed to create copilot-instructions.md:`, e.message);
      }
    }
  }

  // Initialize watchers for all registered projects
  initializeAll() {
    try {
      const settings = getSettings();
      if (settings.projects && settings.projects.length > 0) {
        for (const p of settings.projects) {
          if (p.path && fs.existsSync(p.path) && fs.existsSync(path.join(p.path, '.agents'))) {
            this.getOrCreateWatcher(p.id, p.path);
          }
        }
      }
    } catch (e) {
      console.error('⚠️ Failed to initialize watchers:', e.message);
    }
  }
}

// Singleton
const watcherManager = new WatcherManager();

export { watcherManager, SSEClientManager, POINTER_FILES, POINTER_CONTENT };
