import fs from 'fs';
import path from 'path';
import { ActivityLogger, shouldIgnore } from './activity-logger.js';
import { handleDeletion } from './watcher-restore.js';
import { syncPlanToProgress } from './plan-sync-server.js';
import * as globalStore from './global-store.js';

export const POINTER_CONTENT = `<!-- AUTO-GENERATED by ai-checkpoint. Do not edit. Source of truth: AGENTS.md -->
Read and follow all instructions in AGENTS.md
`;

export const TEMPLATE_RESTORABLE = {
  [path.join('.agents', 'AGENTS.md')]: 'AGENTS.md',
  [path.join('.agents', 'RULES.md')]: 'RULES.md',
  [path.join('.agents', 'SYSTEM_GUIDE.md')]: 'SYSTEM_GUIDE.md',
};

export const POINTER_FILES = ['AGENTS.md'];
export const WARN_ONLY_FILES = [];

export class ProjectWatcher {
  constructor(projectId, projectPath, sseManager, templatesDir) {
    this.projectId = projectId;
    this.projectPath = projectPath;
    this.sseManager = sseManager;
    this.templatesDir = templatesDir;
    this.watchers = [];
    this.debounceTimers = new Map();
    this.isRestoring = false;
    this.logger = new ActivityLogger(projectPath, projectId);
  }

  start() {
    this.watchDirectory(path.join(this.projectPath, '.agents'), '.agents');
    this.watchDirectory(path.join(this.projectPath, 'plan'), 'plan');
    this.watchRootPointerFiles();
    this.watchProjectFiles();
  }

  stop() {
    for (const w of this.watchers) {
      try { w.close(); } catch {}
    }
    this.watchers = [];
    for (const timer of this.debounceTimers.values()) clearTimeout(timer);
    this.debounceTimers.clear();
  }

  watchDirectory(dirPath, prefix) {
    if (!fs.existsSync(dirPath)) return;
    try {
      const watcher = fs.watch(dirPath, { recursive: false }, (eventType, filename) => {
        if (!filename || this.isRestoring) return;
        const relativePath = path.join(prefix, filename);
        this.debounce(relativePath, () => this.handleFileEvent(relativePath, eventType));
      });
      this.watchers.push(watcher);
      watcher.on('error', () => {});
    } catch {}
  }

  watchRootPointerFiles() {
    try {
      const watcher = fs.watch(this.projectPath, { recursive: false }, (eventType, filename) => {
        if (!filename || this.isRestoring) return;
        if (POINTER_FILES.includes(filename)) this.debounce(filename, () => this.handleFileEvent(filename, eventType));
        if (filename === 'AGENTS.md') this.debounce(filename, () => this.handleRootAgentsChange(eventType));
      });
      this.watchers.push(watcher);
      watcher.on('error', () => {});
    } catch {}
  }

  debounce(key, fn) {
    if (this.debounceTimers.has(key)) clearTimeout(this.debounceTimers.get(key));
    this.debounceTimers.set(key, setTimeout(() => { this.debounceTimers.delete(key); fn(); }, 300));
  }

  handleFileEvent(relativePath, eventType) {
    const fullPath = path.join(this.projectPath, relativePath);
    const exists = fs.existsSync(fullPath);

    if (!exists) {
      this.logger.log('DELETED', relativePath);
      const ctx = {
        projectPath: this.projectPath, sseManager: this.sseManager, projectId: this.projectId,
        templatesDir: this.templatesDir, logger: this.logger, setRestoring: (v) => { this.isRestoring = v; }
      };
      handleDeletion(relativePath, ctx);
    } else {
      const action = eventType === 'rename' ? 'CREATED' : 'MODIFIED';
      this.logger.log(action, relativePath);
      this.handleChange(relativePath);
    }

    this.sseManager.broadcast(this.projectId, 'activity-log', {
      ts: new Date().toISOString(), action: exists ? (eventType === 'rename' ? 'CREATED' : 'MODIFIED') : 'DELETED', file: relativePath,
    });
  }

  handleChange(relativePath) {
    if (relativePath.startsWith('plan' + path.sep) && relativePath.endsWith('.md')) {
      try {
        globalStore.backupPlanFile(this.projectId, this.projectPath, path.basename(relativePath));
        syncPlanToProgress(this.projectId, this.projectPath);
      } catch {}
      this.sseManager.broadcast(this.projectId, 'plan-updated', { file: relativePath });
      this.sseManager.broadcast(this.projectId, 'progress-updated', { file: relativePath });
      return;
    }
    if (relativePath === path.join('.agents', 'PROGRESS.md')) {
      this.sseManager.broadcast(this.projectId, 'progress-updated', { file: relativePath });
      return;
    }
    if (relativePath === path.join('.agents', 'AGENTS.md') || relativePath === path.join('.agents', 'RULES.md')) {
      this.sseManager.broadcast(this.projectId, 'config-updated', { file: relativePath });
    }
  }

  handleRootAgentsChange() {
    const fullPath = path.join(this.projectPath, 'AGENTS.md');
    if (!fs.existsSync(fullPath)) {
      this.sseManager.broadcast(this.projectId, 'file-deleted-warning', { file: 'AGENTS.md', message: 'Root AGENTS.md was deleted.', canRestore: false });
    }
  }

  watchProjectFiles() {
    try {
      const watcher = fs.watch(this.projectPath, { recursive: true }, (eventType, filename) => {
        if (!filename || this.isRestoring) return;
        if (filename.startsWith('.agents' + path.sep) || filename === '.agents') return;
        
        // Handle plan directory deletion specifically
        if (filename === 'plan' && !fs.existsSync(path.join(this.projectPath, 'plan'))) {
          this.logger.log('DELETED', 'plan');
          const backupDir = globalStore.getPlanBackupDir(this.projectId);
          if (fs.existsSync(backupDir)) {
            try {
              fs.mkdirSync(path.join(this.projectPath, 'plan'), { recursive: true });
              const files = fs.readdirSync(backupDir);
              for (const f of files) {
                fs.copyFileSync(path.join(backupDir, f), path.join(this.projectPath, 'plan', f));
              }
              this.logger.log('RESTORED', 'plan');
              // Restart watch for plan dir
              this.watchDirectory(path.join(this.projectPath, 'plan'), 'plan');
            } catch (e) {
              console.error('⚠️ Failed to restore plan directory:', e.message);
            }
          }
          return;
        }

        if (filename.startsWith('plan' + path.sep) || filename === 'plan') return;
        if (shouldIgnore(filename)) return;
        
        this.debounce('proj:' + filename, () => {
          const fullPath = path.join(this.projectPath, filename);
          const exists = fs.existsSync(fullPath);
          const action = exists ? (eventType === 'rename' ? 'CREATED' : 'MODIFIED') : 'DELETED';
          this.logger.log(action, filename);
          this.sseManager.broadcast(this.projectId, 'activity-log', { ts: new Date().toISOString(), action, file: filename });
        });
      });
      this.watchers.push(watcher);
      watcher.on('error', () => {});
    } catch {}
  }
}
